In [1]:
import numpy as np

In [2]:
# Juntar dois arrays

array1 = np.arange(20, 25)
array2 = np.arange(15)

array_completo = np.concatenate([array1, array2])

print(array_completo)

[20 21 22 23 24  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
# Separando em dois arrays

array_separado1, array_separado2 = np.split(array_completo, [5])

print(array_separado1)
print(array_separado2)

[20 21 22 23 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
# Colocar novos dados em um array

array_completo = np.append(array_completo, 2000)

array_completo = np.insert(array_completo, 3, 3000)

print(array_completo)

[  20   21   22 3000   23   24    0    1    2    3    4    5    6    7
    8    9   10   11   12   13   14 2000]


In [5]:
# Deletar dados de um array

array_completo = np.delete(array_completo, -1)

print(array_completo)

[  20   21   22 3000   23   24    0    1    2    3    4    5    6    7
    8    9   10   11   12   13   14]


In [6]:
# Reshap

array_3x3 = np.arange(9).reshape(3,3) #Isso aqui é util na hora de fazer regressão linear

print(array_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# Trocando números dentro de uma condição

array_inicial = np.array([4,4,4,4,7,6,5,32,13,2,32,675,75,465])

# Como trocar todos os numeros menores que 40 por 0?

array_inicial[array_inicial < 40] = 0

print(array_inicial)

[  0   0   0   0   0   0   0   0   0   0   0 675  75 465]


In [14]:
# Como ordenar objetos dentro de uma lista?

array_desordenado = np.array([23109, 3249, 349, 20, 3, 5, 12490])

array_crescente = np.sort(array_desordenado)
array_decrescente = -np.sort(-array_desordenado)

print(array_crescente, array_decrescente)

[    3     5    20   349  3249 12490 23109] [23109 12490  3249   349    20     5     3]


# Exercício

- Exercício 34: Peça ao usuário para digitar o lucro da Petrobras, Vale e Weg. Mostre os lucros em ordem do maior para o menor

In [16]:
lucro_weg = float(input("Qual o lucro da Weg? "))
lucro_petrobras = float(input("Qual o lucro da Petrobras? "))
lucro_vale = float(input("Qual o lucro da Vale? "))
array_lucros = np.array([])
array_lucros = np.append(array_lucros, [lucro_weg, lucro_petrobras, lucro_vale])
array_lucros_decrescente = -np.sort(-array_lucros)
print(array_lucros_decrescente)

Qual o lucro da Weg? 50
Qual o lucro da Petrobras? 10
Qual o lucro da Vale? 70
[70. 50. 10.]


In [ ]:
empresas = np.array['Petrobras','Vale','Weg']

array_lucros = np.array([])

for empresa in empresas:
    
    lucro = float(input(f"Digite o lucro da {empresa}: "))
    array_lucros = np.append(array_lucros, lucro)
    
array_lucros_decrescente = -np.sort(-array_lucros)

print(f'Lucro das empresas, do maior para o menor: {array_lucros_}')