In [1]:
import numpy as np

In [2]:
vetor = np.array([1,2,3,4,5,6,7,8,9])

vetor2d = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [3]:
# Posições

print(vetor[0])

print(vetor[0:2])

print(vetor[-1])

print(vetor2d[2][0])

print(vetor2d[0][1])

1
[1 2]
9
7
2


In [5]:
# Filtrando dados

maior_que_5 = vetor[vetor > 5]

somente_par = vetor[vetor % 2 == 0]

igual_a_5 = vetor[vetor == 5]

maior_que_3_menor_que_8 = vetor[(vetor > 3) & (vetor < 8)]

print(maior_que_5)
print(somente_par)
print(igual_a_5)
print(maior_que_3_menor_que_8)

[6 7 8 9]
[2 4 6 8]
[5]
[4 5 6 7]


# Exercício

- Exercício 33: Faça um programa que gere um vetor de retornos positivos positivos ou negativos entre -1 e 1 na quantidade de dias que o usuário escolher. Devolva um vetor dos retornos positivos, o primeiro e o último retorno


In [7]:
quantitade_de_dias = int(input("Digite quantos retornos devem ser gerados: "))
vetor_aleatorio = np.random.uniform(-1, 1, quantitade_de_dias)
somente_positivos = vetor_aleatorio[vetor_aleatorio > 0]
primeiro = vetor_aleatorio[0]
ultimo = vetor_aleatorio[-1]
print(f"Os retornos positivos são {somente_positivos}")
print(f"O primeiro retorno é {primeiro} e o último é {ultimo}")


Digite quantos retornos devem ser gerados: 5
Os retornos positivos são [0.55745496 0.9816182  0.15118031]
O primeiro retorno é -0.5107210635877892 e o último é -0.6062885040789607
